import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { signIn, signOut, useSession } from 'next-auth/react'

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {session ? (
          <>
          {console.log('session', session)}
            <h1>{session?.user?.name}</h1>
            <button type="button" onClick={() => signOut()}>
              Sair
            </button>
          </>
        ) : (
          <>
            {console.log('session', session)}
            <button type="button" onClick={() => signIn('github')}>Entrar</button>
          </>
        )}
      </main>

    </div>
  )
}

export default Home
